name: 'Sync'
description: 'Sync a git directory tracking a separate branch on the same git repo'
inputs:
  syncDir:
    description: 'Directory to git init'
    default: sync
    required: true
  syncBranch:
    description: 'Branch to track in Directory'
    default: sync
    required: true
  token:
    description: >
      Personal access token (PAT) used to clone sync branch.
    default: ${{ github.token }}
    required: true
runs:
  using: "composite"
  steps:
    - name: Download release
      shell: bash
      run: |
        echo "#################################################"
        echo "Changing directory to 'PUBLISH_DIR' ${PUBLISH_DIR} ..."
        cd ${PUBLISH_DIR}

        echo '=================== Publish to Sync branch ==================='
        git add .
        git status
        git commit -m "Automated deployment to sync branch from ${GITHUB_SHA::8}'" > /dev/null 2>&1 || true
        git push deploy ${PUBLISH_BRANCH} --force || git push --set-upstream deploy ${PUBLISH_BRANCH}
        rm -rf .git

        cd ../
        echo '=================== Done  ==================='
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        PUBLISH_DIR: ${{ inputs.syncDir }}
        PUBLISH_BRANCH: ${{ inputs.syncBranch }}
